name: "Bug: Report a Bug With Scope Analysis"
description: Report a bug you encountered with our scope analysis tooling
title: "Scope Analysis: "
labels:
  - bug
  - "package: scope-manager"
  - triage
body:
  - type: checkboxes
    id: sanity-checks
    attributes:
      label: Before You File a Bug Report Please Confirm You Have Done The Following...
      options:
        - label: I have updated to the latest version of the packages.
          required: true
        - label: I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+scope-manager%22) and found none that matched my issue.
          required: true
        - label: I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.
          required: true
  - type: markdown
    id: complexity-note
    attributes:
      value: |
        ## Note For Complex Issues
        If your issue requires some complex repro - such as multiple files or a specific folder structure - please do not use this template.
        Instead, select the ["Report a complex bug with repro repo" template](https://github.com/typescript-eslint/typescript-eslint/issues/new?template=bug-report-complex.yaml), and follow the steps.
  - type: textarea
    id: repro-code
    attributes:
      label: Repro Code
      description: A ***minimal*** code sample which reproduces the issue
      render: typescript
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What did you expect to happen? Please be specific here - list the exact lines and messages you expect.
      placeholder: I expected that the function should foo the bar
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What actually happened? Please be specific here - list the exact lines and messages that caused errors.
      placeholder: The function bar'd the foo instead!
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: Any additional info you'd like to provide.
  - type: textarea
    id: versions
    attributes:
      label: Versions
      render: markdown
      value: |
        | package                                | version |
        | -------------------------------------- | ------- |
        | `@typescript-eslint/scope-manager`     | `X.Y.Z` |
        | `TypeScript`                           | `X.Y.Z` |
        | `ESLint`                               | `X.Y.Z` |
        | `node`                                 | `X.Y.Z` |
    validations:
      required: true
